### PR TITLE
fix: changed flyctl command to work with phoenix app

### PR DESCRIPTION
**Pull request by brecke**
fixes https://github.com/superfly/fly-pr-review-apps/issues/22 as suggested by @amos-kibet

### CODE REVIEW

**Comment by brecke** [comment]
does not work... yet

**Comment by ricksonoliveira** [comment]
@brecke Any news on this?

**Comment by brecke** [comment]
> @brecke Any news on this?

Not really, it was taking too much time and I gave up eventually.

**Comment by ricksonoliveira** [comment]
Same for me, was trying to apply that for a client but it was taking too much of my time. Hopefully the fly team will take a look soon. Thanks.

**Pull request closed without merging**
